# Generated by Django 4.2.6 on 2023-11-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categorie',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Prodotti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('img', models.ImageField(default='prodotti/noimg.png', upload_to='prodotti/%Y/%m/%d/')),
                ('descrizione', models.TextField(blank=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qunatita', models.IntegerField(default=0, verbose_name='Quantità in magazzino')),
                ('pubblicato', models.BooleanField(default=False)),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='shop.categorie')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddIndex(
            model_name='categorie',
            index=models.Index(fields=['nome'], name='shop_catego_nome_4aa0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='prodotti',
            index=models.Index(fields=['id', 'slug'], name='shop_prodot_id_ccea80_idx'),
        ),
        migrations.AddIndex(
            model_name='prodotti',
            index=models.Index(fields=['nome'], name='shop_prodot_nome_243167_idx'),
        ),
        migrations.AddIndex(
            model_name='prodotti',
            index=models.Index(fields=['-data_inserimento'], name='shop_prodot_data_in_2b6373_idx'),
        ),
    ]
