# Generated by Django 4.2.6 on 2023-11-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodotti',
            old_name='qunatita',
            new_name='quantita',
        ),
    ]
