# Generated by Django 4.2.6 on 2023-11-14 08:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_qunatita_prodotti_quantita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodotti',
            options={'ordering': ['nome'], 'verbose_name': 'prodotti', 'verbose_name_plural': 'prodotti'},
        ),
        migrations.AlterField(
            model_name='prodotti',
            name='descrizione',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
