# Generated by Django 4.2.6 on 2023-11-16 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_prodotti_options_alter_prodotti_descrizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='categoria_principale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caegoria_principale', to='shop.categorie'),
        ),
    ]
