# Generated by Django 4.2.6 on 2023-11-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_categorie_categoria_principale'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('slug', 'categoria_principale')},
        ),
    ]
