# Generated by Django 4.2.6 on 2023-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo della slide')),
                ('sottotitolo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sottotitolo della slide')),
                ('corpo', models.TextField(verbose_name='Contenuto della slide')),
                ('img', models.ImageField(blank=True, null=True, upload_to='slide/%Y/%m/', verbose_name='Immagine Slide')),
            ],
        ),
    ]
