# Generated by Django 4.2.6 on 2023-11-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_carouselcat_carousel_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='img',
            field=models.ImageField(blank=True, default='slide/no_img.jpeg', null=True, upload_to='slide/%Y/%m/', verbose_name='Immagine Slide'),
        ),
    ]
