# Generated by Django 4.2.6 on 2023-11-10 15:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_carousel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='corpo',
            field=ckeditor.fields.RichTextField(verbose_name='Contenuto delle slide'),
        ),
    ]
