# Generated by Django 4.2.6 on 2023-11-10 15:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_carousel_corpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='corpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenuto delle slide'),
        ),
    ]
