# Generated by Django 4.2.6 on 2023-11-13 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_alter_carousel_corpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascita', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('tipo_account', models.CharField(choices=[('admin', 'Admin'), ('developer', 'Developer'), ('cliente', 'Cliente')], default='cliente', max_length=50, verbose_name='Tipologi Utente')),
                ('img_profilo', imagekit.models.fields.ProcessedImageField(default='user_profile/profile_user.png', upload_to='upser_profile/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
