# Generated by Django 4.2.6 on 2023-11-13 09:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img_profilo',
            field=imagekit.models.fields.ProcessedImageField(default='user_profile/profile_user.png', upload_to='user_profile/%Y/%m/%d/'),
        ),
    ]
