# Generated by Django 4.2.6 on 2023-11-18 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cap',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Inserisci un C.A.P. valido', regex='^[0-9]{5}$')], verbose_name='C.A.P.'),
        ),
    ]
