# Generated by Django 4.2.6 on 2023-11-03 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorieBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Medici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cognome', models.CharField(max_length=150)),
                ('lugo_nascita', models.CharField(max_length=150, verbose_name='Luogo di Nascita')),
                ('data_nascita', models.DateField(verbose_name='Data di Nascita')),
                ('data_inserimento', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Medici',
            },
        ),
        migrations.CreateModel(
            name='Pazienti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cognome', models.CharField(max_length=150)),
                ('luogo_nascita', models.CharField(max_length=150, verbose_name='Luogo di Nascita')),
                ('data_nascita', models.DateField(verbose_name='Data di Nascita')),
                ('residenza', models.CharField(max_length=150, verbose_name='Comune di Residenza')),
                ('indirizzo', models.CharField(max_length=200)),
                ('data_inserimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('medico', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.medici')),
            ],
            options={
                'verbose_name_plural': 'Pazienti',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=150)),
                ('descrizione', models.CharField(max_length=255)),
                ('corpo', models.TextField()),
                ('img_blog', models.ImageField(blank=True, null=True, upload_to='blogimg/', verbose_name='Immagine di copertina')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.categorieblog')),
            ],
        ),
    ]
