# Generated by Django 4.2.6 on 2023-11-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medici',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
