# Generated by Django 4.2.6 on 2023-10-27 08:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categorieblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=150)),
                ('descrizione', models.CharField(max_length=255)),
                ('corpo', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.categorieblog')),
            ],
        ),
    ]
