# Generated by Django 4.2.6 on 2023-10-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieblog',
            name='descrizione',
            field=models.CharField(default='', max_length=150),
        ),
    ]
