# Generated by Django 4.2.6 on 2023-11-06 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_medici_img_medico_alter_blog_img_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='autore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
