# Generated by Django 4.2.6 on 2023-10-27 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categorieblog_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medici',
            name='data_nascita',
            field=models.DateField(verbose_name='Data di Nascita'),
        ),
        migrations.AlterField(
            model_name='medici',
            name='lugo_nascita',
            field=models.CharField(max_length=150, verbose_name='Luogo di Nascita'),
        ),
        migrations.CreateModel(
            name='Pazienti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cognome', models.CharField(max_length=150)),
                ('luogo_nascita', models.CharField(max_length=150, verbose_name='Luogo di Nascita')),
                ('data_nascita', models.DateField(verbose_name='Data di Nascita')),
                ('residenza', models.CharField(max_length=150, verbose_name='Comune di Residenza')),
                ('indirizzo', models.CharField(max_length=200)),
                ('data_inserimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('medico', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.medici')),
            ],
            options={
                'verbose_name_plural': 'Pazienti',
            },
        ),
    ]
