# Generated by Django 4.2.6 on 2023-11-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_medici_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieblog',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
