# Generated by Django 4.2.6 on 2023-10-26 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=150)),
                ('descrizione', models.CharField(max_length=255)),
                ('corpo', models.TextField()),
                ('data_creazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_ultima_modifica', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Articoli',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('corpo', models.TextField()),
                ('descrizione', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
