# Generated by Django 4.2.6 on 2023-10-26 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=150)),
                ('descrizione', models.CharField(max_length=255)),
                ('corpo', models.TextField()),
                ('data_creazopne', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_ultima_modifica', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
